#!/usr/bin/env python3
"""
Extract table structure from MySQL .frm files
This script reads .frm files and generates CREATE TABLE statements
"""

import os
import struct
import sys

def read_frm_file(frm_path):
    """Read and parse a MySQL .frm file"""
    try:
        with open(frm_path, 'rb') as f:
            # Read the header
            header = f.read(64)
            
            # Extract table name from filename
            table_name = os.path.basename(frm_path).replace('.frm', '')
            
            # Read the rest of the file
            content = f.read()
            
            return {
                'table_name': table_name,
                'header': header,
                'content': content
            }
    except Exception as e:
        print(f"Error reading {frm_path}: {e}")
        return None

def generate_create_table_sql(table_info):
    """Generate CREATE TABLE SQL from .frm info"""
    table_name = table_info['table_name']
    
    # Basic CREATE TABLE statement without indexes
    sql = f"""CREATE TABLE IF NOT EXISTS {table_name} (
    id INT AUTO_INCREMENT PRIMARY KEY,
    -- Add columns here based on .frm analysis
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
"""
    return sql

def main():
    original_db = r'C:\XAMP\mysql\data\bus_system'
    output_file = r'C:\XAMP\htdocs\Bus_system\api\database_recovery_from_frm.sql'
    
    if not os.path.exists(original_db):
        print(f"Error: Original database directory not found: {original_db}")
        return
    
    # Get all .frm files
    frm_files = [f for f in os.listdir(original_db) if f.endswith('.frm')]
    
    if not frm_files:
        print("No .frm files found")
        return
    
    print(f"Found {len(frm_files)} .frm files")
    
    # Generate SQL
    sql_statements = []
    sql_statements.append("-- Database recovery from .frm files")
    sql_statements.append("-- Generated by extract_frm_structure.py")
    sql_statements.append("")
    sql_statements.append("SET FOREIGN_KEY_CHECKS = 0;")
    sql_statements.append("")
    sql_statements.append("CREATE DATABASE IF NOT EXISTS bus_system_recover;")
    sql_statements.append("USE bus_system_recover;")
    sql_statements.append("")
    
    for frm_file in sorted(frm_files):
        frm_path = os.path.join(original_db, frm_file)
        table_info = read_frm_file(frm_path)
        
        if table_info:
            sql = generate_create_table_sql(table_info)
            sql_statements.append(f"-- Table: {table_info['table_name']}")
            sql_statements.append(sql)
            sql_statements.append("")
    
    sql_statements.append("SET FOREIGN_KEY_CHECKS = 1;")
    
    # Write to file
    with open(output_file, 'w') as f:
        f.write('\n'.join(sql_statements))
    
    print(f"SQL generated and saved to: {output_file}")
    print(f"Generated {len(frm_files)} table definitions")

if __name__ == '__main__':
    main()
